{{- if and .Values.jellyfin.tailscale.enabled .Values.jellyfin.tailscale.sidecar.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jellyfin-tailscale

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jellyfin-tailscale
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["{{ .Values.jellyfin.tailscale.sidecar.existingAuthSecret | default "tailscale-auth-secret" }}"]
    verbs: ["get", "update", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jellyfin-tailscale
subjects:
  - kind: ServiceAccount
    name: jellyfin-tailscale
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: jellyfin-tailscale
  apiGroup: rbac.authorization.k8s.io
{{ end }}
