apiVersion: v2
appVersion: 3.1.0
dependencies:
- name: common
  repository: https://k8s-at-home.com/charts/
  version: 1.6.2
description: Free and easy binary newsreader
home: https://github.com/k8s-at-home/charts/tree/master/charts/sabnzbd
icon: https://avatars1.githubusercontent.com/u/960698?s=400&v=4
keywords:
- sabnzbd
- usenet
maintainers:
- email: jeff@billimek.com
  name: billimek
name: sabnzbd
sources:
- https://hub.docker.com/r/linuxserver/sabnzbd/
- https://sabnzbd.org/
version: 3.6.1
