apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sabnzbd.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "sabnzbd.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "sabnzbd.name" . }}
    spec:
      containers:
        - name: sabnzbd
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: PUID
              value: "{{ .Values.env.PUID }}"
            - name: PGID
              value: "{{ .Values.env.PGID }}"
            - name: TZ
              value: "{{ .Values.env.TZ }}"
          volumeMounts:
            - name: config
              mountPath: /config
            - name: downloads
              mountPath: /downloads
      volumes:
        - name: config
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.config.existingClaim }}
        - name: downloads
          nfs:
            server: {{ .Values.persistence.downloads.nfs.server }}
            path: {{ .Values.persistence.downloads.nfs.path }}
